/*+===================================================================
File:      ExamApp.cpp

Summary:   Defines the entry point for the console application.

Classes:   None

Origin:    File generated by Visual Studio project template.

Author:    Charles "C.J." Walls
===================================================================+*/
#include "stdafx.h"
#include "LogOnController.h"
#include "StudentController.h"
#include "ProfessorController.h"
#include "FileRepository.h"

using namespace std;

/*+===================================================================
Function: main

Summary:  Main entry point to application.

Args:     None

Returns:  int
			Indicates how the application exited.  Normal exit is 0.
===================================================================+*/
int main()
{
	// Variable declaration and initialization
	bool isExit = false;
	ExamAppModels::Repository *repository = new ExamAppModels::FileRepository();
	ExamAppControllers::LogOnController *logOnController = new ExamAppControllers::LogOnController(repository);
	ExamAppControllers::StudentController *studentController = new ExamAppControllers::StudentController(repository);
	ExamAppControllers::ProfessorController *professorController = new ExamAppControllers::ProfessorController(repository);

	// Main application loop
	while (!isExit)
	{
		// Present application logon menu
		switch (logOnController->logOn())
		{
		case ExamAppModels::LogOnRoles::Unknown:
			break;
		case ExamAppModels::LogOnRoles::Student:
			 studentController->setStudent(logOnController->getAuthenticatedStudent());
			 studentController->logInAsStudent();
			break;
		case ExamAppModels::LogOnRoles::Professor:
			professorController->logInAsProfessor();
			break;
		case ExamAppModels::LogOnRoles::Exit:
			isExit = true;
		default: break;
		}
	}
	
	// Clean-up
	delete professorController;
	delete studentController;
	delete logOnController;
	delete repository;

    return 0;
}

